url: "https://codurance.com"
domains: 
   en: "https://codurance.com"
   es: "https://codurance.es"
highlighter: rouge 
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes

exclude: ["README.md", "_posts_TOFIX", "vendor"]

author_dir: publications/author

sitename: "Codurance"
subtitle: "craft at heart"
email: "hello@codurance.com"
office:
  bcn:
    phone: +34 689 723 737
  lnd:
    phone: +44 207 4902967

tag_page_layout: tag_page
tag_page_dir: publications/tag
tag_page_layout: tag

collections:
  newsletters:
    output: true
  posts:
    output: true
  videos:
    output: true
  events:
    output: true

pagination:
  enabled: true
  per_page: 10
  paginate_path: "/page:num"
  sort_reverse: true 

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate-v2
  - jekyll-multiple-languages-plugin


exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "_posts"]

default_post_image: "/assets/img/custom/home/computerdesk_original_opt_bw.jpg"
