url: "https://codurance.com"
domains: 
   en: "https://codurance.com"
   es: "https://codurance.es"
highlighter: rouge 
permalink: pretty
markdown: rdiscount
rdiscount:
  extensions:
    - footnotes     # footnotes

exclude: ["README.md", "_posts_TOFIX", "vendor"]

author_dir: pubications/author

tag_page_layout: tag_page
tag_page_dir: publications/tag
tag_page_layout: tag

paginate: 10
paginate_path: "/publications/page:num"

sitename: "Codurance"
subtitle: "craft at heart"
email: "info@codurance.com"

googleanalytics:
  account: UA-46289079-1

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["en", "es"]
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "_posts"]

