version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3-jessie-node
      environment:
        FOLDER_NAME: "site-$CIRCLE_BRANCH"
        WEBSITE_INDEX_DOCUMENT: index.html
        AWS_REGION: eu-west-1
        BUCKET_NAME: codurance-site-pr
        PREVIEW_URL: "http://$BUCKET_NAME.s3-website-eu-west-1.amazonaws.com/$FOLDER_NAME/$WEBSITE_INDEX_DOCUMENT"
  dependencies:
    cache_directories:
      - "/opt/circleci/.rvm/gems"
    pre:
      - npm install --global pug
      - gem install bundler
      - gem install rspec-core -v '3.4.1'
      - gem install jekyll
      - sudo apt-get install jq
      - aws configure set preview.cloudfront true
      - bundle install
  compile:
    override:
      - _utility/build_site_prb.sh $FOLDER_NAME
  test:
    override:
      - /bin/true
  deployment:
    production:
      branch: /^master$/
      commands:
        - _utility/deploy_en_site.sh
        - _utility/deploy_es_site.sh
    pullrequest:
      branch: /^.*/
      commands:
        - _utility/deploy_prb.sh $FOLDER_NAME
        - _utility/create_commit_status.sh "$CIRCLE_PROJECT_USERNAME" "$CIRCLE_PROJECT_REPONAME" "$GITHUB_TOKEN" "$PREVIEW_URL" "$CIRCLE_SHA1"
      
