version: 2.0

references:
  common_info: &common_info
    working_directory: ~/codurance/site
    parallelism: 1
    shell: /bin/bash --login

  deploy_info: &deploy_info
    environment:
      WEBSITE_INDEX_DOCUMENT: index.html
      AWS_REGION: eu-west-1
      BUCKET_NAME: codurance-site-pr

jobs:
  build:
    <<: *common_info
    docker:
      - image: codurance/website_build_base
    steps:
      - run: echo 'export FOLDER_NAME=site-${CIRCLE_BRANCH}' >> $BASH_ENV
      - checkout
      - run: _utility/build_site_prb.sh $FOLDER_NAME
      - persist_to_workspace:
          root: .
          path: 

  production:
    <<: *common_info
    <<: *deploy_info
    docker:
      - image: codurance/website_deployment_base
    steps:
      - attach_workspace:
          at: .
      - run: |
          echo 'export FOLDER_NAME=site-${CIRCLE_BRANCH}' >> $BASH_ENV
          echo 'export PREVIEW_URL=http://${BUCKET_NAME}.s3-website-eu-west-1.amazonaws.com/${FOLDER_NAME}/${WEBSITE_INDEX_DOCUMENT}' >> $BASH_ENV
      - run: aws configure set preview.cloudfront true
      - run: _utility/deploy_en_site.sh
      - run: _utility/deploy_es_site.sh
  pullrequest:
    <<: *common_info
    <<: *deploy_info
    docker:
      - image: codurance/website_deployment_base
    steps:
      - attach_workspace:
          at: .
      - run: |
          echo 'export FOLDER_NAME=site-${CIRCLE_BRANCH}' >> $BASH_ENV
          echo 'export PREVIEW_URL=http://${BUCKET_NAME}.s3-website-eu-west-1.amazonaws.com/${FOLDER_NAME}/${WEBSITE_INDEX_DOCUMENT}' >> $BASH_ENV
      - run: aws configure set preview.cloudfront true
      - run: _utility/deploy_prb.sh $FOLDER_NAME
      - run: _utility/create_commit_status.sh $CIRCLE_PROJECT_USERNAME $CIRCLE_PROJECT_REPONAME $GITHUB_TOKEN $PREVIEW_URL $CIRCLE_SHA1

workflows:
  version: 2
  build:
    jobs:
      - build
  prod:
    jobs:
      - production:
          requires:
            - build
          filters:
            branches:
              only: master
  pre:
    jobs:
      - pullrequest:
          requires:
            - build
          filters:
            branches:
              ignore: master
